version: "3"
services:
  neo4j:
    container_name: neo4j
    build:
      context: ./neo4j
    restart: always
    ports:
      - 7474:7474
      - 7687:7687
    #env_file:
    #  - .env
    #  args:
    #    NGINX_ENV: devneo4j
    restart: always

