version: "3"
services:
  neo4j:
    container_name: exercise_neo4j
    build: ./neo4j
    ports:
      - 7474:7474
      - 7687:7687
    restart: always
  jupyter:
    container_name: exercise_jupyter
    build: ./jupyter
    volumes:
      - ./jupyter/notebooks:/home/jovyan
    ports:
      - 8888:8888
